### ISSUE TITLE
webClient failed to resolve 'https://snippets.glot.io'

### ISSUE THREAD

**Issue by kuoho** [vert-x3/vertx-guide-for-java-devs#76]
`webClient = WebClient.create(vertx, new WebClientOptions()
            .setSsl(true)
            .setUserAgent("vert-x3"));`

`webClient.post(443, "snippets.glot.io", "/snippets")
                    .putHeader("Content-Type", "application/json")
                    .as(BodyCodec.jsonObject()) 
                    .sendJsonObject(payload, ar -> {...}`

17:23:10.009 [vert.x-eventloop-thread-3] ERROR i.v.s.c.http.HttpServerVerticle - HTTP Client error
java.net.UnknownHostException: failed to resolve 'snippets.glot.io'. Exceeded max queries per resolve 4 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:856)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:228)
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/1.1.1.1:53] query via UDP timed out after 5000 milliseconds (no stack trace available)

it looks like a stale bug. not happened to everyone?

**Comment by jponge** [comment]
Just tested and the service is up and running. 

Perhaps you are behind a faulty DNS server.

**Comment by kuoho** [comment]
> Just tested and the service is up and running.
> 
> Perhaps you are behind a faulty DNS server.

Yes, I set 1.1.1.1 as the preferred DNS server
